# Generated by Django 3.0.6 on 2022-01-18 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sure_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('transporter', models.CharField(max_length=15)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=40)),
                ('wish', models.TextField(blank=True, max_length=500)),
                ('total_price', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('В наявності', 'В наявності'), ('Товар відсутный', 'Товар відсутный')], max_length=50)),
                ('old_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivering.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('unit_id', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('number', models.PositiveIntegerField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivering.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('mark', models.IntegerField(blank=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('text', models.TextField()),
                ('data', models.DateTimeField()),
                ('audit', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivering.Product')),
            ],
        ),
        migrations.CreateModel(
            name='BoughtProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('producer', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('number', models.PositiveIntegerField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivering.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivering.Product')),
            ],
        ),
    ]
