# Generated by Django 3.0.4 on 2020-03-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6),
            preserve_default=False,
        ),
    ]
