# Generated by Django 3.0.4 on 2020-03-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0003_auto_20200329_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.3, max_digits=3),
            preserve_default=False,
        ),
    ]
