# Generated by Django 3.0.4 on 2020-03-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0005_auto_20200329_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coffee',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
