# Generated by Django 3.0.4 on 2020-04-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0006_product_coffee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='total_price',
        ),
    ]
