# Generated by Django 3.0.4 on 2020-04-02 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0007_auto_20200402_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coffee',
        ),
    ]
