# Generated by Django 3.0.4 on 2020-04-02 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0010_remove_product_milk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivering.Product')),
            ],
        ),
    ]
