# Generated by Django 3.0.4 on 2020-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0012_auto_20200404_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/img/foto1.jpg', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='image',
            field=models.ImageField(default='static/img/foto1.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
