# Generated by Django 3.0.4 on 2020-04-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0014_auto_20200404_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Donuts', 'Donuts'), ('Waffles', 'Waffles'), ('Coffee', 'Coffee')], default='Donuts', max_length=50),
            preserve_default=False,
        ),
    ]
