# Generated by Django 3.0.4 on 2020-04-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0015_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.CharField(default='slug', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
