# Generated by Django 3.0.4 on 2020-04-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0016_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=500),
        ),
    ]
