# Generated by Django 3.0.4 on 2020-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0017_auto_20200407_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
