# Generated by Django 3.0.4 on 2020-04-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0019_auto_20200408_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
