# Generated by Django 3.0.4 on 2020-04-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0021_auto_20200408_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pollination',
        ),
        migrations.RemoveField(
            model_name='product',
            name='taste',
        ),
    ]
