# Generated by Django 3.0.4 on 2020-04-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0025_auto_20200415_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproduct',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
