# Generated by Django 3.0.4 on 2020-04-15 19:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0026_auto_20200415_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
