# Generated by Django 3.0.4 on 2020-04-17 12:18

from django.db import migrations, models
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0032_selectedproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, default=Decimal(1)),
        ),
    ]
