# Generated by Django 3.0.4 on 2020-04-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0034_remove_selectedproduct_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproduct',
            name='price',
            field=models.IntegerField(),
        ),
    ]
