# Generated by Django 3.0.4 on 2020-04-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0038_auto_20200417_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproduct',
            name='amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=1),
            preserve_default=False,
        ),
    ]
