# Generated by Django 3.0.4 on 2020-04-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0040_auto_20200419_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
