# Generated by Django 3.0.6 on 2020-05-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0042_auto_20200423_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_way', models.CharField(max_length=50)),
                ('getting_products', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sure_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('wish', models.TextField(blank=True, max_length=500)),
                ('total_price', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
