# Generated by Django 3.0.6 on 2020-06-21 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0045_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='getting_products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_way',
        ),
    ]
