# Generated by Django 3.0.6 on 2020-06-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0046_auto_20200621_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedproduct',
            name='session',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
