# Generated by Django 3.0.6 on 2020-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0047_selectedproduct_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtproduct',
            name='session',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selectedproduct',
            name='session',
            field=models.CharField(max_length=200),
        ),
    ]
