# Generated by Django 3.0.6 on 2020-07-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0048_auto_20200623_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='session',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
