# Generated by Django 3.0.6 on 2020-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0049_comment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='audit',
            field=models.BooleanField(default=False),
        ),
    ]
