# Generated by Django 3.0.6 on 2022-01-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0051_auto_20220113_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_way',
        ),
    ]
