# Generated by Django 3.0.6 on 2022-01-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0055_auto_20220114_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='glaze',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='boughtproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='boughtproduct',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='selectedproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='selectedproduct',
            name='weight',
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='boughtproduct',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('В наявності', 'В наявності'), ('Товар відсутный', 'Товар відсутный')], default='В наявності', max_length=50),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='selectedproduct',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
