# Generated by Django 3.0.6 on 2022-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivering', '0056_auto_20220114_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('В наявності', 'В наявності'), ('Товар відсутный', 'Товар відсутный')], max_length=50),
        ),
    ]
